name: Automated Build

on:
  push:
    branches:
      - master

env:
  THERION_VERSION: 5.4.4
  THERION_PATH: ./therion-5.4.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Therion
        id: cache-therion
        uses: actions/cache@v1
        with:
          path: ${{ env.THERION_PATH }}/bin
          key: ${{ runner.os }}-${{ env.THERION_VERSION }}
      #========================= INSTALL DEPENDENCIES ========================#
      - name: Install Therion compilation dependencies
        if: steps.cache-therion.outputs.cache-hit != 'true'
        run: sudo apt install -y bwidget lcdf-typetools libtk-img-dev libtk-img libvtk6-dev libvtk6.3 libwxgtk3.0-dev tcl-dev survex texlive-latex-base # Pre-installed: gcc ghostscript imagemagick libfreetype6-dev libjpeg-dev libpng-dev zlib1g zlib1g-dev
      - name: Install Therion runtime dependencies
        run: sudo apt install -y libproj-dev texlive-metapost
      - name: Download and unpack Therion
        if: steps.cache-therion.outputs.cache-hit != 'true'
        run: |
          curl https://github.com/therion/therion/archive/v${THERION_VERSION}.tar.gz -L -O
          tar xvzf v${THERION_VERSION}.tar.gz
      - name: Build Therion
        if: steps.cache-therion.outputs.cache-hit != 'true'
        run: |
          make -C $THERION_PATH
          mkdir ${THERION_PATH}/bin
          mv ${THERION_PATH}/therion ${THERION_PATH}/bin/therion
      - name: Install svgo
        run: sudo npm install -g svgo
      #=========================== GENERATE OUTPUT ===========================#
      - name: Generate Primadonna output files
        run: ${THERION_PATH}/bin/therion data/_config/automation/prima_ubend_mona.thconfig
      - name: Generate Vrtnarija output files
        run: ${THERION_PATH}/bin/therion data/_config/automation/vrtnarija.thconfig
      - name: Generate Old System output files
        run: ${THERION_PATH}/bin/therion data/_config/automation/m2m16m18.thconfig
      - name: Generate Migovec System output files
        run: ${THERION_PATH}/bin/therion data/_config/automation/system_migovec.thconfig
      #=========================== COMPRESS OUTPUT ===========================#
      - name: Compress PDFs
        run: |
          for file in ./data/_outputs/*.pdf; do
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=temp.pdf $file;                                    
            mv temp.pdf $file;
          done
      - name: Compress SVGs
        run: svgo -f ./data/_outputs/
      #=========================== CREATE LISTING ===========================#
      - name: Create listing
        run: python3 ./scripts/_outputs/create_file_listing.py ./data/_outputs/ ./data/_outputs/listing.jso
      #=============================== UPLOADS ===============================#
      - name: Upload Files
        uses: "rhyst/automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: Build ${{ github.run_number }}
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ./data/_outputs/listing.json
            ./data/_outputs/*.3d
            ./data/_outputs/*.lox
            ./data/_outputs/*.pdf
            ./data/_outputs/*.svg
