name: Automated Build

on:
  push:
    branches:
      - master

env:
  THERION_VERSION: 5.4.4
  THERION_PATH: ./therion-5.4.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Therion
        id: cache-therion
        uses: actions/cache@v1
        with:
          path: ${{ env.THERION_PATH }}/bin
          key: ${{ runner.os }}-${{ env.THERION_VERSION }}
      #========================= INSTALL DEPENDENCIES ========================#
      - name: Install Therion compilation dependencies
        if: steps.cache-therion.outputs.cache-hit != 'true'
        run: sudo apt install -y bwidget lcdf-typetools libtk-img-dev libtk-img libvtk6-dev libvtk6.3 libwxgtk3.0-dev tcl-dev survex texlive-latex-base # Pre-installed: gcc ghostscript imagemagick libfreetype6-dev libjpeg-dev libpng-dev zlib1g zlib1g-dev
      - name: Install Therion runtime dependencies
        run: sudo apt install -y libproj-dev texlive-metapost
      - name: Download and unpack Therion
        if: steps.cache-therion.outputs.cache-hit != 'true'
        run: |
          curl https://github.com/therion/therion/archive/v${THERION_VERSION}.tar.gz -L -O
          tar xvzf v${THERION_VERSION}.tar.gz
      - name: Build Therion
        if: steps.cache-therion.outputs.cache-hit != 'true'
        run: |
          make -C $THERION_PATH
          mkdir ${THERION_PATH}/bin
          mv ${THERION_PATH}/therion ${THERION_PATH}/bin/therion
      #=========================== GENERATE OUTPUT ===========================#
      - name: Generate Primadonna output files
        run: ${THERION_PATH}/bin/therion data/_config/automation/prima_ubend_mona.thconfig
      - name: Generate Vrtnarija output files
        run: ${THERION_PATH}/bin/therion data/_config/automation/vrtnarija.thconfig
      #============================ CREATE RELEASE ===========================#
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: build-${{ github.run_number }}
      #    release_name: Build ${{ github.run_number }}
      #    draft: false
      #    prerelease: false
      #=============================== UPLOADS ===============================#
      - name: Upload Files
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: Build ${{ github.run_number }}
          automatic_release_tag: "latest"
          files: |
            ./data/_outputs/primadona_ubend_monatip.3d
            ./data/_outputs/primadona_ubend_monatip_plan_SLO.pdf
            ./data/_outputs/primadona_ubend_monatip_plan_ENG.pdf
            ./data/_outputs/primadona_ubend_monatip_EE_SLO.pdf
            ./data/_outputs/primadona_ubend_monatip_EE_ENG.pdf
            ./data/_outputs/vrtnarija.3d
            ./data/_outputs/vrtnarija_plan_SLO.pdf
            ./data/_outputs/vrtnarija_plan_ENG.pdf
      # Primadonna
      #- name: Upload Primadonna 3D
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/primadona_ubend_monatip.3d
      #    asset_name: primadona_ubend_monatip.3d
      #    asset_content_type: application/octet-stream
      #- name: Upload Primadonna plan SLO
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/primadona_ubend_monatip_plan_SLO.pdf
      #    asset_name: primadona_ubend_monatip_plan_SLO.pdf
      #    asset_content_type: application/pdf
      #- name: Upload Primadonna plan ENG
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/primadona_ubend_monatip_plan_ENG.pdf
      #    asset_name: primadona_ubend_monatip_plan_ENG.pdf
      #    asset_content_type: application/pdf
      #- name: Upload Primadonna EE SLO
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/primadona_ubend_monatip_EE_SLO.pdf
      #    asset_name: primadona_ubend_monatip_EE_SLO.pdf
      #    asset_content_type: application/pdf
      #- name: Upload Primadonna EE ENG
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/primadona_ubend_monatip_EE_ENG.pdf
      #    asset_name: primadona_ubend_monatip_EE_ENG.pdf
      #    asset_content_type: application/pdf
      # Vrtnarija
      #- name: Upload Vrtnarija 3D
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/vrtnarija.3d
      #    asset_name: vrtnarija.3d
      #    asset_content_type: application/octet-stream
      #- name: Upload Vrtnarija plan SLO
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/vrtnarija_plan_SLO.pdf
      #    asset_name: vrtnarija_plan_SLO.pdf
      #    asset_content_type: application/pdf
      #- name: Upload Vrtnarija plan ENG
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./data/_outputs/vrtnarija_plan_ENG.pdf
      #    asset_name: vrtnarija_plan_ENG.pdf
      #    asset_content_type: application/pdf
